name: Deploy Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run:  |
          npm install
          
      - name: Configure Git user
        run:  |
          git config --global user.email "abelard.rodlens@gmail.com"
          git config --global user.name "AbelardRodlens"
        
      - name: Build project
        run:  |
          npm run build

      - name: Deploy to Github Pages
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/AbelardRodlens/portfolio-react.git
          npm run deploy
